# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "jekyll", "~> 3.9.3"

gem "jekyll-remote-theme", "~> 0.4.3"

gem "jekyll-seo-tag", "~> 2.8"

gem "webrick", "~> 1.8"

gem "github-pages", "~> 228", group: :jekyll_plugins
